INSERT INTO salons (name, slug, phone, adm_name, agent_name, max_barbers) VALUES ('Empresa Dois','empresa-dois','329999','Maria','Ana',3);
INSERT INTO users (salon_id,name,email,password_hash) VALUES (2,'Dona Dois','dois@x.com',crypt('senhasenha',gen_salt('bf',10)));
INSERT INTO categories (salon_id,name) VALUES (1,'Cabelo'),(2,'Unhas'),(2,'Cabelo');
INSERT INTO services (salon_id,name,price,duration_min,category_id) VALUES (2,'Manicure',40,60,(SELECT id FROM categories WHERE salon_id=2 AND name='Unhas'));
INSERT INTO barbers (salon_id,name) VALUES (2,'Joana');
INSERT INTO barber_schedules (barber_id,weekday,start_time,end_time) SELECT id,1,'09:00','18:00' FROM barbers WHERE salon_id=2;
INSERT INTO barber_categories SELECT id,(SELECT id FROM categories WHERE salon_id=2 AND name='Unhas') FROM barbers WHERE salon_id=2;
INSERT INTO customers (salon_id,name,phone) VALUES (2,'Cliente Dois','553288887777'),(1,'Cliente Extra','553299990000');
INSERT INTO agent_commands (salon_id,kind,phrase,phrase_norm) VALUES (1,'pause','Will aqui','will aqui'),(2,'off','Maria sai','maria sai');
INSERT INTO agent_attendants (salon_id,name,name_norm) VALUES (1,'Claudia','claudia');
INSERT INTO waitlist (salon_id,customer_id,barber_id,desired_at) SELECT 1,id,NULL,now()+interval '3 day' FROM customers WHERE salon_id=1 LIMIT 1;
